Dev
KlishevichIlya/FrontEnd pull request #1
Opened 2020-04-14 13:49 UTC by KlishevichIlya

У меня тема "Создание портфолио", я сделал главную страницу ( еще пока не добавил footer, но скоро это сделаю). Макет я Вам показывал еще на паре. Вы говорили, что 2 лаба это чисто HTML, но я применял и CSS.(если будет необходимо, то для следующей страницы я отправлю сначала HTML, а потом CSS). 
Ссылка для открытия страницы: https://klishevichilya.github.io/portfolio.github.io/

2020-04-14 13:57 UTC, gmltA commented
@KlishevichIlya А вы жадаеце паступова кожную старонку мне паказваць, ці мне дачакацца, пакуль вы некалькі асноўных зробіце і потым ужо прымаць як лабу цалкам?

2020-04-14 14:02 UTC, KlishevichIlya commented
У меня всего будет 3 страницы(главная,вход/выход, создание портфолио). Если
Вас не затруднит, то хотелось бы, чтобы вы посмотрели эту страницу и
сказали какие-то недочёты или ошибки. В будущем буду отправлять сразу
несколько.
P.S. И хотелось бы уточнить, можно ли делать сразу страницу с CSS? Или Вы
не будете такое принимать, т.к. хотите видеть все постепенно.

вт, 14 апр. 2020 г. в 16:57, Alex Avetsiuk <notifications@github.com>:

> @KlishevichIlya <https://github.com/KlishevichIlya> А вы жадаеце
> паступова кожную старонку мне паказваць, ці мне дачакацца, пакуль вы
> некалькі асноўных зробіце і потым ужо прымаць як лабу цалкам?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/KlishevichIlya/FrontEnd/pull/1#issuecomment-613458812>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AKL72VZ4G36MCHQN6RJCCI3RMRTVTANCNFSM4MHYFKNA>
> .
>

2020-04-14 14:15 UTC, gmltA commented
Добра, тады будзем глядзець паступова.

Скажу так: рабіць старонку адразу са стылямі прасцей, але ёсць верагоднасць, што прыйдзецца мяняць нешта ў HTML. Калі вас гэта не пужае можаце рабіць адразу з CSS — я пагляджу і тое, і тое.

2020-04-14 14:20 UTC, KlishevichIlya commented
Хорошо, я тогда буду делать сразу со стилями.
А Вы посмотрите страницу, которую я отправил? И нужен ли footer на каждой
странице?

вт, 14 апр. 2020 г. в 17:15, Alex Avetsiuk <notifications@github.com>:

> Добра, тады будзем глядзець паступова.
>
> Скажу так: рабіць старонку адразу са стылямі прасцей, але ёсць
> верагоднасць, што прыйдзецца мяняць нешта ў HTML. Калі вас гэта не пужае
> можаце рабіць адразу з CSS — я пагляджу і тое, і тое.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/KlishevichIlya/FrontEnd/pull/1#issuecomment-613468839>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AKL72V3BBQV4D6ASEVXACA3RMRVZVANCNFSM4MHYFKNA>
> .
>

2020-04-14 14:32 UTC, gmltA requested changes
Нядрэнна. Чакаем наступнай порцыі.

2020-04-14 14:32 UTC, gmltA commented on main.html
> +		<ul>
Здаецца, тут можна выкарыстаць тэг `nav`.

2020-04-14 14:32 UTC, gmltA commented on main.html
> +		<div class = "creator">
Лепей увесь спіс CV абвярнуць у `ul`. Семантычна гэта ж менавіта спіс у вас атрымліваецца?..

Плюс лепей зрабіць яго такім, каб ён павялічваўся, пакуль яму хапае на гэта месца: такім чынам больш картак можна будзе змясціць на адным радку.

2020-04-14 14:32 UTC, gmltA commented on main.html
> +			<a class = "creator-link"  href="#open_portfolio1"></a>
Хутчэй за ўсё, вам спатрэбіцца дадатковая інфармацыя ў картке аднаго CV, інакш незразумела, як карыстальнік будзе адрозневаць іх. Раю дадаць туды прынамсі пазіцыю і дату стварэння.

2020-04-14 14:32 UTC, gmltA commented on main.html
> +		<div class = "opener">
Замест таго, каб пазіцыяніраваць `a` унутры `div` праз `position: absolute`, лепей зрабіце наадварот:

```HTML
<a>
  <div></div>
</a>
```

Такім чынам увесь блок аўтаматычна стане клікабельным.

2020-04-14 14:32 UTC, gmltA commented on style.css
> +    height: 50px;
А чаму ў вас рознай атрымалася вышыня гэтай і наступнай кнопак?

2020-04-14 14:32 UTC, gmltA commented on style.css
>      overflow: hidden;
Навошта тут `overflow`?

2020-04-14 14:32 UTC, gmltA commented on style.css
> +    float: left;
Давайце адразу накіруемся на вёрстку без `float` — гэта стары кастыль, замест якога зараз ёсць куды больш зручныя flexbox i grid.

2020-04-14 14:32 UTC, gmltA commented on style.css
> +.main-phrase h1:before {
👍 цікавы элемент)

2020-04-14 14:34 UTC, gmltA commented
> И нужен ли footer на каждой странице?

Залежыць ад таго, як вы стылістычна вырашыце. Я б прапанаваў зрабіць нешта накшталт капірайту і, напрыклад, спасылку на профіль стваральніка.

2020-04-14 14:44 UTC, KlishevichIlya commented on style.css
> +    height: 50px;
Т.к. если у кнопки #exit поставить 50px, то картинка прижимается полностью к краю нав. панели. В то время как у #portfolio не прижата.

2020-04-14 14:53 UTC, gmltA commented on style.css
> +    height: 50px;
Дык зрабіце ці выявы аднолькавымі, ці спазіцыяніруйце па-іншаму background, ці унутраны водступ у элеменце зрабіце.

Плюс, здаецца мне, можна вынесці стыль кнопкі у гэтай панелі ў асобны клас (у ім будзе, напрыклад, памер зададзены). А ў сэлектарах, звязаных з ID кнопкі толькі выяву мяняць.

2020-04-16 16:56 UTC, KlishevichIlya commented
Создал страницу для входа. Главную страницу еще отредактирую по Вашим замечаниям.(сделаю в ближайшее время).
Ссылка для открытия страницы: https://klishevichilya.github.io/loginpage.github.io/

2020-04-16 18:11 UTC, gmltA requested changes

2020-04-16 18:11 UTC, gmltA commented on enter.css
> +    height: 100vh;
Лепей так не рабіць. Розныя браўзеры па-рознаму вылічваюць гэтую велічыню. Напрыклад, мабільныя браўзеры мяняюць вышыню viewport у залежнасці ад таго, ці бачна тулбары. Сафары ўвогуле лічыць у тым ліку месца, якое хаваецца за імі.

2020-04-16 18:11 UTC, gmltA commented on enter.css
> +    height: 100vh;
Плюс у вас ёсць дэфолтны `padding`. У выніку старонка ўсё роўна мае скробблар.

2020-04-16 18:11 UTC, gmltA commented on enter.css
> +	font-family: sans-serif;
Стылі тэксту лепей адразу задаваць дакументу (`font-family`, `line-height`, 'letter-spacing' і г.д.). А яшчэ ў вас, хутчэй за ўсё, будзе адзін агульны файл стыляў (бо сайт будзе SPA), таму разлічвайце на гэта адразу: рабіце стылі, якія будуць выкарыстоўвацца кампанентамі на розных старонках (напрыклад кнопкі і інпуты).
Ну і стылістычна ў вас атрымліваюцца зусім розныя старонкі. Зрабіце ўжо іх у падобным стылю.

2020-04-16 18:11 UTC, gmltA commented on enter.css
> +.button:hover{
Прачытайце [вось гэта](https://medium.com/@eatmeplzzz/%D1%81%D1%82%D0%B8%D0%BB%D0%B8%D0%B7%D1%83%D0%B9%D1%82%D0%B5-%D1%81%D0%BE%D1%81%D1%82%D0%BE%D1%8F%D0%BD%D0%B8%D1%8F-hover-focus-%D0%B8-active-%D0%BF%D0%BE-%D1%80%D0%B0%D0%B7%D0%BD%D0%BE%D0%BC%D1%83-41964eb81b6c), калі ласка.

2020-04-17 13:49 UTC, KlishevichIlya commented on enter.css
> +	font-family: sans-serif;
Скажите, а можно оставить на данный момент два .css файла, т.к. придется достаточно много переделать, чтобы поместить все в один .css файл?
А сделать общими, допустим,стили текстов и их цвет. Или обязательное условие, чтобы был один .css файл?

2020-04-17 19:59 UTC, KlishevichIlya commented
Для страницы входа исправил все Ваши замечания. Также добавил размытое фоновое изображение.(оказалось сложнее, чем я предполагал) 
Для основной страницы также внёс большинство правок. Кроме правок по поводу плиток(ячеек портфолио), сделаю это в ближайшее время.
P.S. Жду Вашей оценки внесенных правок обеих страниц.
Ссылки на страницы:
https://klishevichilya.github.io/loginpage.github.io/
https://klishevichilya.github.io/portfolio.github.io/

2020-04-18 09:52 UTC, gmltA commented on enter.css
> +	font-family: sans-serif;
Можаце пакінуць, але потым будзе трошкі складаней. Вы ж можаце адразу яго далучаць да двух старонак. Да і класы агульныя для некалькіх старонак выкарыстоўваць.

2020-04-18 09:54 UTC, gmltA commented
Не хочацца моцна крытыкаваць, але мінулы стыль старонкі са спісам CV лепей быў. Ён выглядаў як адзінае цэлае, штоль. А зараз у вас месіва атрымалася =(

2020-04-18 09:56 UTC, gmltA commented
> Также добавил размытое фоновое изображение.

Добра, што вы прапрактыкаваліся ў гэтым. На будучыню: калі нейкі эфект павінен быць на выяве заўсёды, лепей адразу ў фоташопе зрабіць гэты blur на выяве і ў такім выглядзе яе выкарыстоўваць. Так і сайт хутчэй працаваць будзе, і эфект, як у вас зараз на межах выявы, знікне. Але калі гэты эфект аніміраваць захочаце, тады, канешне, `filter` — добрая магчымасць.

2020-04-18 10:00 UTC, gmltA requested changes

2020-04-18 10:00 UTC, gmltA commented on enter.css
> +	position: absolute;
А чаму вы не на `body` выяву дадалі?

2020-04-18 10:00 UTC, gmltA commented on enter.html
> +	<section class ="section">
Не сказаў бы, што тут мае сэнс гэты тэг выкарыстоўваць. Калі вам парэбен нейкі кантэйнер — можаце выкарыстаць `main`, але я б раіў проста стылі bg пеанесці на body.

2020-04-20 14:55 UTC, KlishevichIlya commented
В странице логирования заменил <section> на <main>. (Стиль bg не стал пихать в body, т.к. я пытался до этого использовать blur в body и в итоге у меня размывалось переднее изображение. Применил section т.к. нашел такой способ в Гугле:) ).
Начал изменять страницу портфолио. Решил на всю карточку сделать кликабельное изображение, а сверху над карточкой указывать название проекта, либо это "карточка создания нового портфолио". (Изначально ориентировался на дизайн Pages в IPhone и хотел сделать нечто похожее). Если это дизайн также не подойдёт, не могли бы Вы скинуть ссылку или скрин сайта, с похожими карточками? (т.к. я с карточками нагуглил только интернет-магазины).
И еще вопрос: можно ли убрать свечение по краям на странице логирования? (также не смог это нагуглить)

2020-04-20 16:09 UTC, gmltA commented
> не могли бы Вы скинуть ссылку или скрин сайта, с похожими карточками?

Як варыянт можаце што-небудзь такое зрабіць:
![image](https://user-images.githubusercontent.com/138737/79773299-f8470580-8339-11ea-9ec3-39e05ffca716.png)

> И еще вопрос: можно ли убрать свечение по краям на странице логирования?

Вось таму я раю вам адразу зрабіць адпаведную выяву і выкарыстаць яе ў якасці фону. Без фільтраў. А так можаце толькі колер змяніць. Напрыклад зрабіць `background` у `body` чорным.

2020-04-24 13:21 UTC, KlishevichIlya commented
Переделал главную страницу. Сделал карточки по Вашему примеру. Мне кажется, что сейчас наиболее удачный вариант получился. Карточка содержит название портфолио, дату создания, описание и аватарку автора. Также в этом коммите был добавлен footer с ссылками на соц.сети.
Посмотреть страницу можно тут: https://klishevichilya.github.io/portfolio.github.io/
Напишите, пожалуйста, есть ли у Вас какие-то замечания по данной странице и могу ли я приступать к написанию последней?

2020-04-25 13:56 UTC, gmltA commented
> Переделал главную страницу. Сделал карточки по Вашему примеру. Мне кажется, что сейчас наиболее удачный вариант получился. Карточка содержит название портфолио, дату создания, описание и аватарку автора. Также в этом коммите был добавлен footer с ссылками на соц.сети.
> Посмотреть страницу можно тут: https://klishevichilya.github.io/portfolio.github.io/
> Напишите, пожалуйста, есть ли у Вас какие-то замечания по данной странице и могу ли я приступать к написанию последней?

![image](https://user-images.githubusercontent.com/138737/80281691-a0334900-8715-11ea-8965-8a09aab089b5.png)

У мяне ўсё верна са стылямі?)

2020-04-25 14:02 UTC, KlishevichIlya commented
![card](https://user-images.githubusercontent.com/43515223/80281791-5ac34b80-8716-11ea-8661-58d65fca258a.jpg)
У меня это выглядит вот так. А из-за чего может быть такая ошибка?

2020-04-25 14:03 UTC, gmltA commented
> ![card](https://user-images.githubusercontent.com/43515223/80281791-5ac34b80-8716-11ea-8661-58d65fca258a.jpg)
> У меня это выглядит вот так. А из-за чего может быть такая ошибка?

Памылка ў тым, што ўся картка ў вас — флекс кантэйнер, у якім вы спрабуеце адразу ў двух вымярэннях блокі выстаўляць. Тут найлешы варыянт — выкарыстаць grid.

2020-04-25 14:08 UTC, gmltA commented
```CSS
    display: grid;
    grid-template-areas:
        "img title"
        "img date"
        "desc desc";
```

А далей вам трэба праз `grid-area` куды трэба раскласці вашыя дадзеныя ўнутры карткі. Ну і стылі выправіць.

2020-04-25 14:08 UTC, KlishevichIlya commented
Я прочитаю про grid и постараюсь исправить проблему. Скажите, а есть еще какие-то недочеты или ошибки на данном этапе?

2020-04-25 14:11 UTC, gmltA commented
> Я прочитаю про grid и постараюсь исправить проблему. Скажите, а есть еще какие-то недочеты или ошибки на данном этапе?

Яшчэ можаце з памерам тэксту на картке пагуляцца (як на прыкладзе). Не абавязкова, каб ён быў аднолькавы. І ніжні тэкст па леваму боку лепей выраўняць.

![image](https://user-images.githubusercontent.com/138737/80282006-b80bcc80-8717-11ea-9410-d4d3193bd46a.png)

У такім стане колер тэксту рэжа вочы. Складана чытаць.

2020-04-25 16:54 UTC, KlishevichIlya commented
Поменял в карточку flex на grid. Также немного изменил текст. Мне кажется, что на этом фоне красный цвет будет самым читабельным. 
Ссылка для просмотра:https://klishevichilya.github.io/portfolio.github.io/

2020-04-27 12:19 UTC, gmltA commented
> Поменял в карточку flex на grid. Также немного изменил текст. Мне кажется, что на этом фоне красный цвет будет самым читабельным.
> Ссылка для просмотра:https://klishevichilya.github.io/portfolio.github.io/

Колер зараз лепей, але з'явілася вось што

![image](https://user-images.githubusercontent.com/138737/80371260-47d98400-889a-11ea-819b-3a786770ad2c.png)

2020-04-27 13:40 UTC, KlishevichIlya commented
А если я просто прижму к нижней границе grid название портфолио? Этот способ не подойдет?

2020-04-27 16:10 UTC, gmltA commented
> А если я просто прижму к нижней границе grid название портфолио? Этот способ не подойдет?

Не разумею, шчыра кажучы, пра што вы. Паглядзіце на мой мінулы камент. Калі так зробіце, гэтая праблема таксама вырашыцца.

2020-04-27 16:15 UTC, KlishevichIlya commented
![image](https://user-images.githubusercontent.com/43515223/80394792-07d6c900-88bb-11ea-8de9-a58be3bab3b4.png)
Сейчас моя надпись прижата к самому верху cells, если я эту надпись прижму к нижней границе ячейки, это не решит мою проблему?
И еще хотелось бы узнать, как мне тестировать, что у меня ничего "не уезжает", чтобы Вам не скидывать кучу неправильных коммитов? Потому что у меня на экране даже предыдущий вариант выглядел нормально

2020-04-27 16:33 UTC, gmltA commented
> Сейчас моя надпись прижата к самому верху cells, если я эту надпись прижму к нижней границе ячейки, это не решит мою проблему?

Не дапаможа. Вам трэба ці памер элементу з тэкстам абмяжоўваць (каб тэкст аўтаматычна скарачаўся `text-overflow`), ці па-іншаму задаць памер слупкоў сеткі.

> И еще хотелось бы узнать, как мне тестировать, что у меня ничего "не уезжает", чтобы Вам не скидывать кучу неправильных коммитов?

У эмулятары хрома можаце пару варыянтаў памеру інтэрфейса паспрабаваць. Звычайна, калі вёрстка зроблена правільна, большасць з такіх памылак вылазіць не будзе.

2020-04-29 11:29 UTC, KlishevichIlya commented
Переделал структуру карточки (все сделал как Вы написали, убрал box и классы в теге a, но оставил классы для того чтобы убрать подчеркивания текста и чтобы убрать метки списка). Также применил text-overflow. (На сколько я понял, он может работать только с однострочным текстом. Там вроде бы есть какие-то костыли, чтобы применить для много строчного, но я решил, что для названия достаточно однострочного).
P.S. Вроде бы сейчас ничего не съезжает, но, возможно, я опять этого не вижу.
Ссылка для просмотра: https://klishevichilya.github.io/portfolio.github.io/

2020-04-29 15:46 UTC, gmltA commented
> применил text-overflow. (На сколько я понял, он может работать только с однострочным текстом. Там вроде бы есть какие-то костыли, чтобы применить для много строчного, но я решил, что для названия достаточно однострочного).

Верна. Ёсць пакуль што не стандартызаваны цалкам [line-clamp](https://caniuse.com/#search=line-clamp), але можна яго не выкарыстоўваць пакуль што.

2020-04-29 15:53 UTC, gmltA requested changes

2020-04-29 15:53 UTC, gmltA commented on style.css
> +  text-overflow: clip;
Вось толькі замест `clip` лепей было б выкарыстоўваць `ellipsis`. У такім выпадку карыстальнік бачыць, што тэксту цалкам не хапіла месца. А зараз вы яго проста абразаеце.

2020-04-29 15:53 UTC, gmltA commented on style.css
>    align-self: end;
```suggestion
  align-self: center;
```

2020-04-29 15:53 UTC, gmltA commented on style.css
> +
```suggestion
margin: 0;
```

2020-04-29 15:56 UTC, KlishevichIlya commented on style.css
> +  text-overflow: clip;
Я сразу использовал ellipsis, но мне не понравилось как оно выглядело, поэтому заменил на clip. Могу заменить обратно

2020-04-29 16:03 UTC, KlishevichIlya commented on style.css
>    align-self: end;
Сначала просто пытался всунуть класс clip внутрь item-name, потом понял, что лучше вынести в отдельный класс. А т.к. text-overflow работает с overflow:hidden, то добавил его и забыл удалить.

2020-04-29 16:07 UTC, KlishevichIlya commented
А в остальном стало все более-менее смотрибельным?
И, если всё хорошо, могу ли я мержить в master ветку, исправив Ваши замечания?
P.S. Я когда Вам отвечал, случайно (на сколько я это понял) коммит комментария сделал? И стоит ли его удалить?

2020-04-29 16:09 UTC, gmltA commented on style.css
> +  text-overflow: clip;
Лепей вярнуць. Шчыра кажучы, я б картку ўсё ж трошкі яшчэ падправіў бы. Мае сэнс дадаць знешні `padding`, каб тэкст не дахадзіў да яе меж, а саму картку трошкі павялічыў бы, бо на гэтай старонке шмат пустога месца, а карысны кантэнт зажаты на такім невялічкім кавалку старонкі.

2020-04-29 16:11 UTC, gmltA approved these changes
Добра. Можаце выпраўляць апошнія каменты і мержыць.

2020-04-29 16:11 UTC, gmltA commented
> Я когда Вам отвечал, случайно (на сколько я это понял) коммит комментария сделал? И стоит ли его удалить?

Забейце)

2020-04-29 16:13 UTC, gmltA commented
А, стоп. А наступныя старонкі вы будзеце ў іншым пул-реквесце рабіць?

2020-04-29 16:17 UTC, KlishevichIlya commented
Нет, хотел в этом же ( осталась страница заполнения резюме). Я просто думал
approved можно дать  на определенные коммиты, если нет, то завтра я покажу
Вам ещё страницу заполнения.

ср, 29 апр. 2020 г. в 19:13, Alex Avetsiuk <notifications@github.com>:

> А, стоп. А наступныя старонкі вы будзеце ў іншым пул-реквесце рабіць?
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/KlishevichIlya/FrontEnd/pull/1#issuecomment-621313091>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AKL72VZFJPUYONQRGEKJNOLRPBG4FANCNFSM4MHYFKNA>
> .
>

2020-04-29 16:20 UTC, gmltA commented
> Я просто думал approved можно дать на определенные коммиты

Нажаль так нельга.

Добра, тады чакаю далей)

2020-04-29 16:23 UTC, KlishevichIlya commented
И ещё хотелось бы спросить, вообще есть шансы допуститься к экзамену или Вы
будете принимать лабораторные до начала зачетной недели?) ( как некоторые
преподаватели)

ср, 29 апр. 2020 г. в 19:20, Alex Avetsiuk <notifications@github.com>:

> Я просто думал approved можно дать на определенные коммиты
>
> Нажаль так нельга.
>
> Добра, тады чакаю далей)
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/KlishevichIlya/FrontEnd/pull/1#issuecomment-621316889>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AKL72V7XTJKP7BMCSMW2HB3RPBHUXANCNFSM4MHYFKNA>
> .
>

2020-04-29 16:36 UTC, gmltA commented
Я пакуль не планаваў спыняць прыём. Таму пакуль што шанцаў хапае.

2020-05-04 17:24 UTC, KlishevichIlya commented
Доделал последнюю страницу сайта. Я все-таки почитал, как организовать с помощью JS создание новой секции с опытом работы, если у человека было несколько мест работы, и постараюсь это сделать. На данной странице множество полей ввода, постарался их стилизовать, чтобы не было совсем просто(и грустно). Сделал стилизованный radio(цвета имеют значения). Дизайн смотрел на Работа.TUT.by, поэтому в разделе "Опыт" именно такой дизайн. Мне кажется он вполне информативен и удобен. В конце формы span, по которому будет открывать новая пустая форма ( почему span, а не button, если честно, я не знаю. На тут бае был span и я решил использовать span. Возможно Вы проясните эту ситуацию, почему там используется span). 
Ссылка для просмотра страницы: https://klishevichilya.github.io/edit.github.io/

2020-05-04 18:50 UTC, gmltA commented
> На тут бае был span и я решил использовать span. Возможно Вы проясните эту ситуацию, почему там используется span).

Бо пісалі людзі, якія дрэнна вучыліся вярстаць) У дадзеным выпадку лепей выкарыстоўваць `<button>`

2020-05-04 18:57 UTC, gmltA requested changes

2020-05-04 18:57 UTC, gmltA commented on edit.html
> +				<label class="edit-label">Фамилия</label>
У лэйбла павнен прысутнічаць атрыбут `for`, інакш адсутнічае семантычная сувязь паміж тэкстам у ім і інпутам.

2020-05-04 19:17 UTC, KlishevichIlya commented on edit.html
> +				<label class="edit-label">Фамилия</label>
Исправлю это и span. А по дизайну особых замечаний нет? И могу ли я приступать к медиазапросам, чтобы сделать мобильную версию?

2020-05-05 13:59 UTC, KlishevichIlya commented
Исправил все замечания, а также сделал мобильную версию сайта под IPhone 6/7/8 Plus. Вроде бы все проверил, все выглядит более-менее аккуратно и различимо. 
Ссылки на страницы:
https://klishevichilya.github.io/loginpage.github.io/
https://klishevichilya.github.io/portfolio.github.io/
https://klishevichilya.github.io/edit.github.io/

2020-05-05 18:21 UTC, gmltA requested changes
![image](https://user-images.githubusercontent.com/138737/81101173-67b21d00-8f16-11ea-8147-4182d4fa87dc.png)

Неяк у вас усё паехала

2020-05-05 18:21 UTC, gmltA commented on style.css
> +  height: 2800px;
Гэта што такое??? У вас кантэйнер аўтаматычна атрымае вышыню, каб для ўсяго кантэнту месца хапала.

2020-05-05 21:25 UTC, KlishevichIlya commented on style.css
> +  height: 2800px;
Моя жёсткая ошибка(
Даже и оправдаться никак не могу...

2020-05-06 12:30 UTC, KlishevichIlya commented
Исправил допущенные ошибки выше. Добавил страницу регистрации.
Ссылки для просмотра:
https://klishevichilya.github.io/registration.github.io/
https://klishevichilya.github.io/loginpage.github.io/
https://klishevichilya.github.io/portfolio.github.io/
https://klishevichilya.github.io/edit.github.io/

2020-05-06 15:37 UTC, gmltA requested changes
![image](https://user-images.githubusercontent.com/138737/81195630-c6cf6a80-8fc6-11ea-8f4c-b7535b927646.png)

Зрабіце гэтыя інпуты, калі ласка, такой жа шырыні, як і астатнія. І каб толькі вышыню можна было мяняць.

2020-05-06 15:37 UTC, gmltA commented on style.css
>    justify-content: row;
Гэта як увогуле?

2020-05-06 15:37 UTC, gmltA commented on style.css
> +  height: auto;
Можаце проста выдаліць гэты радок.

2020-05-06 15:44 UTC, KlishevichIlya commented
Не знаю почему, но Вам пришел какой-то старый код, у меня таких строчек нет. + меня удивляет дизайн textarea, потому что у меня это не так выглядит

2020-05-06 15:48 UTC, KlishevichIlya commented
Я сейчас зашел в свой репозиторий Frontend, и там нет таких строк кода. 
![image](https://user-images.githubusercontent.com/43515223/81198185-dbf9c880-8fc9-11ea-9038-fb54e3800b65.png)
![image](https://user-images.githubusercontent.com/43515223/81198258-f2078900-8fc9-11ea-922f-4688cb949b76.png)
P.S. по поводу justify-content:row, это строки соскочили, в одной из попыток, но в главном комите такого нет. + я вроде бы еще раз посмотрел страницы, у меня ничего не съезжает. Подскажите, пожалуйста, что это такое?)

2020-05-06 15:49 UTC, gmltA commented
Так, я на сайце менавіта гэта знайшоў.

2020-05-06 15:50 UTC, gmltA commented
![image](https://user-images.githubusercontent.com/138737/81198720-7c4fed00-8fca-11ea-8138-9aca108cb931.png)

2020-05-06 15:53 UTC, KlishevichIlya commented
Извиняюсь, не изменил то, что переехало в медиазапросах. Могу я перезалить, чтобы Вы еще раз посмотрели?

2020-05-06 15:54 UTC, gmltA commented
> Извиняюсь, не изменил то, что переехало в медиазапросах. Могу я перезалить, чтобы Вы еще раз посмотрели?

Так, канешне.

2020-05-06 16:18 UTC, KlishevichIlya commented
Исправленная версия №2, посмотрите, пожалуйста

2020-05-06 16:31 UTC, gmltA approved these changes
Шырыню `textarea` змяніце і можна працаваць далей. Ітак на 78 элементаў расцягнулі issue ужо)

2020-05-06 16:34 UTC, KlishevichIlya commented
Скажите, а может Вам можно где-то задавать вопросы помимо Github. Есть некоторые вопросы, которые возникли при написании, пытался гуглить, но не понял как с этим справиться.

2020-05-06 16:46 UTC, gmltA commented
Можаце ў Telegram пісаць.

2020-05-06 16:47 UTC, KlishevichIlya commented
Дайте, пожалуйста, Ваш ник

ср, 6 мая 2020 г. в 19:46, Alex Avetsiuk <notifications@github.com>:

> Можаце ў Telegram пісаць.
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/KlishevichIlya/FrontEnd/pull/1#issuecomment-624761896>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AKL72VZEKTI3YHRVEEA6LK3RQGH6FANCNFSM4MHYFKNA>
> .
>

2020-05-06 16:53 UTC, gmltA commented
Такі ж, як і тут.

2020-06-01 18:54 UTC, closed without merging